# Generated by Django 4.2 on 2023-05-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
